update linux installs

diff --git a/bin/apt-install b/bin/apt-install
--- a/bin/apt-install
+++ b/bin/apt-install
@@ -1,4 +1,4 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 
 ! command-exists apt && exit
 
@@ -30,7 +30,17 @@ curl -s https://packagecloud.io/install/repositories/datawireio/telepresence/scr
 
 sudo apt update
 
+failed=()
 packages="$(cat ${DOTPATH}/etc/apt/Packages)"
 for package in ${packages}; do
-    sudo apt install -y ${package}
+    if ! sudo apt install -y ${package}; then
+        failed+=("${package}")
+    fi
 done
+
+if (( ${#failed[@]} > 0 )); then
+    echo
+    echo "Failed to install the following packages!"
+    printf '\t%s\n' "${failed[@]}"
+    exit 1
+fi
diff --git a/bin/pip-install b/bin/pip-install
--- a/bin/pip-install
+++ b/bin/pip-install
@@ -1,7 +1,18 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 
 ! command-exists pip3 && exit
 
+failed=()
 packages="$(cat ${DOTPATH}/etc/pip/Packages)"
+for package in ${packages}; do
+    if ! pip3 install ${package}; then
+        failed+=("${package}")
+    fi
+done
 
-pip3 install ${packages}
+if (( ${#failed[@]} > 0 )); then
+    echo
+    echo "Failed to install the following packages!"
+    printf '\t%s\n' "${failed[*]}"
+    exit 1
+fi
diff --git a/bin/snap-install b/bin/snap-install
--- a/bin/snap-install
+++ b/bin/snap-install
@@ -1,10 +1,20 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 
 ! command-exists snap && exit
 
 sudo snap refresh
 
+failed=()
 packages="$(cat ${DOTPATH}/etc/snap/Packages)"
 for package in ${packages}; do
-    sudo snap install --classic ${package}
+    if ! sudo snap install --classic ${package}; then
+        failed+=("${package}")
+    fi
 done
+
+if (( ${#failed[@]} > 0 )); then
+    echo
+    echo "Failed to install the following packages!"
+    printf '\t%s\n' "${failed[@]}"
+    exit 1
+fi
