linux changes

diff --git a/bin/env-setlocal b/bin/env-setlocal
--- a/bin/env-setlocal
+++ b/bin/env-setlocal
@@ -1,17 +1,26 @@
 #!/usr/bin/env sh
 
+. sh-is-subshell && echo "$0 must be sourced" && exit
+
 if [ -z "$1" ]; then
-    2&> echo "environment variable name is required."
+    >&2 echo "environment variable name is required."
     return 1
 fi
 
 var=${1}
-val=$(eval 'echo $'${var})
-if [ -z "${val}" ]; then     
-    echo "${var} not set!"
-    read -p "Enter a value for ${var}: " val
-    if [ ! -z "${val}" ]; then
-        printf "\nexport ${var}='${val}'\n" >> "${HOME}/.bashrc.local"
-        . "${HOME}/.bashrc.local"
-    fi
+val=$(sed -n "s/^export ${var}=\(.*\)/\1/p" "${HOME}/.bashrc.local")
+
+if [ -n "${val}" ]; then
+    read -p "enter ${var} (${val}): " entered
+else
+    read -p "enter ${var}: " entered
+fi
+
+if [ -n "${entered}" ]; then
+    val="${entered}"
+fi
+
+if [ -n ${val} ]; then
+    set-line "export ${var}=" "export ${var}=${val}" "${HOME}/.bashrc.local"
+    . "${HOME}/.bashrc.local"
 fi
